/**
 * Quantum Game Extraction & Synthesis Utility
 * Detects, parses, and formats interactive games generated by Quantum STEM AI.
 */

export interface DetectedGame {
  title: string;
  code: string;
  instructions: string;
  difficulty: "Normal" | "Medium" | "Hard" | "Extreme";
  genre: string;
  controls: {
    desktop: string;
    mobile: string;
  };
}

/**
 * Checks if a text response contains an interactive playable game.
 */
export function extractGameFromResponse(text: string): DetectedGame | null {
  if (!text) return null;

  // 1. Look for HTML code block with game indicators
  const htmlBlockRegex = /```(?:html|htm)?\s*([\s\S]*?<!DOCTYPE html[\s\S]*?<\/html>[\s\S]*?)```/i;
  const match = text.match(htmlBlockRegex);

  let rawHtmlCode = "";
  if (match && match[1]) {
    rawHtmlCode = match[1].trim();
  } else {
    // Try matching any html block containing canvas or game logic
    const genericHtmlMatch = /```(?:html)?\s*([\s\S]*?<canvas[\s\S]*?<\/script>[\s\S]*?)```/i;
    const m2 = text.match(genericHtmlMatch);
    if (m2 && m2[1]) {
      rawHtmlCode = m2[1].trim();
    }
  }

  // Also check if text mentions game keywords or prompt
  const hasGameKeywords =
    /(?:game\s+loop|requestanimationframe|score|player|gameover|game\s*over|canvas\.getcontext)/i.test(
      rawHtmlCode || text
    ) ||
    /do\s+you\s+want\s+to\s+play\s+the\s+game\s+you\s+created/i.test(text);

  if (!rawHtmlCode && !hasGameKeywords) {
    return null;
  }

  // If no complete HTML code found but game was created/discussed, wrap javascript canvas if present
  if (!rawHtmlCode) {
    const jsMatch = text.match(/```(?:javascript|js)\s*([\s\S]*?(?:canvas|requestanimationframe)[\s\S]*?)```/i);
    if (jsMatch && jsMatch[1]) {
      rawHtmlCode = wrapJsInHtmlGame(jsMatch[1].trim());
    }
  }

  if (!rawHtmlCode) return null;

  // Extract Title from HTML title or text heading
  let title = "Quantum Arcade Odyssey";
  const titleMatch = rawHtmlCode.match(/<title>([^<]+)<\/title>/i);
  if (titleMatch && titleMatch[1]) {
    title = titleMatch[1].trim();
  } else {
    const headingMatch = text.match(/###\s*(?:Game:?\s*)?([^\n]+)/i);
    if (headingMatch && headingMatch[1]) {
      title = headingMatch[1].replace(/Direct Answer:?/i, "").trim();
    }
  }

  // Detect difficulty
  let difficulty: DetectedGame["difficulty"] = "Hard";
  if (/extreme|nightmare|impossible|hardcore/i.test(text + rawHtmlCode)) {
    difficulty = "Extreme";
  } else if (/difficult|hard|fast-paced|challenging|intense/i.test(text + rawHtmlCode)) {
    difficulty = "Hard";
  } else if (/medium|moderate/i.test(text + rawHtmlCode)) {
    difficulty = "Medium";
  } else if (/easy|simple|basic/i.test(text + rawHtmlCode)) {
    difficulty = "Normal";
  }

  // Detect genre
  let genre = "Arcade Physics";
  if (/platformer|jump|gravity/i.test(title + text)) genre = "2D Platformer";
  else if (/space|galaxy|orbital|asteroid|shooter|invader/i.test(title + text)) genre = "Sci-Fi Space Shooter";
  else if (/snake|hyper-snake|cyberpunk/i.test(title + text)) genre = "Cyberpunk Arcade";
  else if (/breaker|brick|pong|paddle/i.test(title + text)) genre = "Physics Brick Breaker";
  else if (/flappy|fly|bird/i.test(title + text)) genre = "Physics Reflex Runner";
  else if (/maze|dungeon|rpg/i.test(title + text)) genre = "Quantum Maze Runner";

  // Build controls summary
  const controls = {
    desktop: "Arrow Keys / WASD to Navigate, Spacebar to Jump / Fire, P to Pause",
    mobile: "On-Screen Touch Virtual D-Pad & Action Buttons",
  };

  // Build instructions
  let instructions = `### Objective:
Control your player to survive, collect quantum energy cores, and eliminate obstacles. 

### Controls:
- **Desktop/Laptop**: Use **Arrow Keys** or **W, A, S, D** for movement. Press **Spacebar** to shoot or jump. Press **P** to pause.
- **Mobile/Phone**: Use the on-screen **Virtual Touch D-Pad** and action buttons.

### Survival & Scoring:
- Score increases as you survive waves and clear targets.
- Collect glowing quantum energy orbs for multiplier bonuses and shields.
- Avoid hazards and enemy collisions to preserve your structural integrity.`;

  // Look for custom instructions in the message text
  const instructionsMatch = text.match(/(?:####\s*How\s+to\s+Play[\s\S]*?)(?=####|###|$)/i);
  if (instructionsMatch && instructionsMatch[0]) {
    instructions = instructionsMatch[0].trim();
  }

  // Ensure full HTML boilerplate
  const completeCode = ensureFullHtmlGameBoilerplate(rawHtmlCode, title);

  return {
    title,
    code: completeCode,
    instructions,
    difficulty,
    genre,
    controls,
  };
}

/**
 * Wraps pure JS game snippet into a self-contained HTML5 Canvas sandbox.
 */
function wrapJsInHtmlGame(jsCode: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>Quantum Synthesized Game</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; user-select: none; }
    body {
      background: #020617;
      color: #00F2FF;
      font-family: system-ui, -apple-system, sans-serif;
      overflow: hidden;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh;
      width: 100vw;
    }
    #gameContainer {
      position: relative;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      width: 100%;
      height: 100%;
    }
    canvas {
      background: #050B14;
      border: 1px solid rgba(0, 242, 255, 0.3);
      box-shadow: 0 0 25px rgba(0, 242, 255, 0.15);
      border-radius: 8px;
      max-width: 98vw;
      max-height: 90vh;
    }
  </style>
</head>
<body>
  <div id="gameContainer">
    <canvas id="gameCanvas" width="800" height="600"></canvas>
  </div>
  <script>
    ${jsCode}
  </script>
</body>
</html>`;
}

/**
 * Enhances HTML game code with responsive scaling, sound effects, and focus handling.
 */
function ensureFullHtmlGameBoilerplate(html: string, title: string): string {
  let processed = html;

  if (!processed.includes("<!DOCTYPE html>")) {
    processed = `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\n<title>${title}</title>\n</head>\n<body>\n${processed}\n</body>\n</html>`;
  }

  // Inject keyboard listener focus & mobile viewport safety if missing
  if (!processed.includes("window.focus()")) {
    const focusScript = `
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        window.focus();
        const canvas = document.querySelector('canvas');
        if (canvas) {
          canvas.setAttribute('tabindex', '0');
          canvas.focus();
          canvas.addEventListener('click', () => canvas.focus());
        }
      });
    </script>
    `;
    processed = processed.replace("</body>", `${focusScript}\n</body>`);
  }

  return processed;
}
