/**
 * Quantum Project Extraction & Synthesis Utility
 * Detects, parses, and formats interactive games and websites generated by Quantum STEM AI in Build Mode.
 */

export interface DetectedProject {
  id: string;
  type: "game" | "website";
  title: string;
  code: string;
  instructions?: string;
  difficulty?: "Normal" | "Medium" | "Hard" | "Extreme";
  genre?: string;
  framework?: string;
  controls?: {
    desktop: string;
    mobile: string;
  };
  features?: string[];
}

/**
 * Checks if a text response contains an interactive playable game or website.
 */
export function extractProjectFromResponse(text: string): DetectedProject | null {
  if (!text) return null;

  // 1. Look for HTML code block
  const htmlBlockRegex = /```(?:html|htm)?\s*([\s\S]*?<!DOCTYPE html[\s\S]*?<\/html>[\s\S]*?)```/i;
  const match = text.match(htmlBlockRegex);

  let rawHtmlCode = "";
  if (match && match[1]) {
    rawHtmlCode = match[1].trim();
  } else {
    // Try matching any html block containing canvas, body, or full web structure
    const genericHtmlMatch = /```(?:html)?\s*([\s\S]*?<(?:canvas|body|div|section|main)[\s\S]*?<\/(?:script|div|html)>[\s\S]*?)```/i;
    const m2 = text.match(genericHtmlMatch);
    if (m2 && m2[1]) {
      rawHtmlCode = m2[1].trim();
    }
  }

  // Check if text mentions game or website keywords
  const isGamePrompt =
    /(?:game\s+loop|requestanimationframe|canvas\.getcontext|do\s+you\s+want\s+to\s+play\s+the\s+game)/i.test(
      rawHtmlCode || text
    ) ||
    /game|arcade|platformer|shooter|snake|flappy|asteroids/i.test(text);

  const isWebsitePrompt =
    /(?:website|landing\s+page|portfolio|dashboard|web\s+app|e-commerce|storefront|do\s+you\s+want\s+to\s+preview\s+the\s+website)/i.test(
      rawHtmlCode || text
    );

  if (!rawHtmlCode && !isGamePrompt && !isWebsitePrompt) {
    return null;
  }

  // If no complete HTML code found but JS canvas was created, wrap it
  if (!rawHtmlCode && isGamePrompt) {
    const jsMatch = text.match(/```(?:javascript|js)\s*([\s\S]*?(?:canvas|requestanimationframe)[\s\S]*?)```/i);
    if (jsMatch && jsMatch[1]) {
      rawHtmlCode = wrapJsInHtmlGame(jsMatch[1].trim());
    }
  }

  if (!rawHtmlCode) return null;

  // Extract Title from HTML title or text heading
  let title = isGamePrompt ? "Quantum Arcade Odyssey" : "Quantum Modern Web Application";
  const titleMatch = rawHtmlCode.match(/<title>([^<]+)<\/title>/i);
  if (titleMatch && titleMatch[1]) {
    title = titleMatch[1].trim();
  } else {
    const headingMatch = text.match(/###\s*(?:Game:?|Website:?|Project:?)?\s*([^\n]+)/i);
    if (headingMatch && headingMatch[1]) {
      title = headingMatch[1].replace(/Direct Answer:?/i, "").trim();
    }
  }

  // Determine Project Type
  const isGame =
    isGamePrompt ||
    /<canvas/i.test(rawHtmlCode) ||
    /requestanimationframe/i.test(rawHtmlCode) ||
    /player\.|gameover/i.test(rawHtmlCode);

  const projectType: "game" | "website" = isGame ? "game" : "website";

  // Detect difficulty for games
  let difficulty: DetectedProject["difficulty"] = "Hard";
  if (/extreme|nightmare|impossible|hardcore/i.test(text + rawHtmlCode)) {
    difficulty = "Extreme";
  } else if (/difficult|hard|fast-paced|challenging|intense/i.test(text + rawHtmlCode)) {
    difficulty = "Hard";
  } else if (/medium|moderate/i.test(text + rawHtmlCode)) {
    difficulty = "Medium";
  } else if (/easy|simple|basic/i.test(text + rawHtmlCode)) {
    difficulty = "Normal";
  }

  // Detect genre or framework
  let genre = "Arcade Physics";
  if (projectType === "game") {
    if (/platformer|jump|gravity/i.test(title + text)) genre = "2D Physics Platformer";
    else if (/space|galaxy|orbital|asteroid|shooter|invader/i.test(title + text)) genre = "Sci-Fi Space Shooter";
    else if (/snake|hyper-snake|cyberpunk/i.test(title + text)) genre = "Cyberpunk Arcade";
    else if (/breaker|brick|pong|paddle/i.test(title + text)) genre = "Physics Brick Breaker";
    else if (/flappy|fly|bird/i.test(title + text)) genre = "Physics Reflex Runner";
    else if (/maze|dungeon|rpg/i.test(title + text)) genre = "Quantum Maze Adventure";
  }

  let framework = "Vanilla HTML5 + Modern CSS + Web Audio";
  if (projectType === "website") {
    if (/tailwind/i.test(rawHtmlCode)) framework = "HTML5 + Tailwind CSS + Responsive UI";
    else if (/bootstrap/i.test(rawHtmlCode)) framework = "HTML5 + Responsive Grid UI";
    else framework = "Modern HTML5 + Cyberpunk CSS + Interactive JS";
  }

  // Build controls or features
  const controls = {
    desktop: "Arrow Keys / WASD to Navigate, Spacebar to Jump / Fire, P to Pause",
    mobile: "On-Screen Touch Virtual D-Pad & Action Buttons",
  };

  const features: string[] = [];
  if (isGame) {
    features.push("60 FPS Smooth Canvas Game Loop", "Web Audio API Sound Synthesizer", "Dynamic Particle FX", "Score & High-Score Tracking");
  } else {
    features.push("Fully Responsive Viewports (Desktop, Tablet, Mobile)", "Modern Cyberpunk & Glassmorphic Styling", "Interactive JavaScript State Management", "Zero External Dependencies Required");
  }

  // Instructions
  let instructions = isGame
    ? `### How to Play:
- **Desktop/Laptop**: Use **Arrow Keys** or **W, A, S, D** for movement. Press **Spacebar** to shoot or jump. Press **P** to pause.
- **Mobile/Phone**: Use on-screen virtual touch buttons.
- Collect energy cores and survive increasing difficulty waves!`
    : `### How to Test this Web Application:
- Click the interactive navigation links and buttons.
- Test responsive viewports using the Desktop, Tablet, and Mobile buttons.
- Download the single-file HTML or copy the code directly to host anywhere.`;

  const instructionsMatch = text.match(/(?:####\s*(?:How\s+to\s+Play|How\s+to\s+Use)[\s\S]*?)(?=####|###|$)/i);
  if (instructionsMatch && instructionsMatch[0]) {
    instructions = instructionsMatch[0].trim();
  }

  // Ensure full HTML boilerplate
  const completeCode = ensureFullHtmlProjectBoilerplate(rawHtmlCode, title, isGame);

  return {
    id: `project_${Date.now()}`,
    type: projectType,
    title,
    code: completeCode,
    instructions,
    difficulty,
    genre,
    framework,
    controls,
    features,
  };
}

/**
 * Wraps pure JS game snippet into a self-contained HTML5 Canvas sandbox.
 */
function wrapJsInHtmlGame(jsCode: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>Quantum Synthesized Game</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; user-select: none; }
    body {
      background: #020617;
      color: #00F2FF;
      font-family: system-ui, -apple-system, sans-serif;
      overflow: hidden;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh;
      width: 100vw;
    }
    #gameContainer {
      position: relative;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      width: 100%;
      height: 100%;
    }
    canvas {
      background: #050B14;
      border: 1px solid rgba(0, 242, 255, 0.3);
      box-shadow: 0 0 25px rgba(0, 242, 255, 0.15);
      border-radius: 8px;
      max-width: 98vw;
      max-height: 90vh;
    }
  </style>
</head>
<body>
  <div id="gameContainer">
    <canvas id="gameCanvas" width="800" height="600"></canvas>
  </div>
  <script>
    ${jsCode}
  </script>
</body>
</html>`;
}

/**
 * Enhances HTML code with full doctype, responsive tags, and canvas autofocus.
 */
function ensureFullHtmlProjectBoilerplate(html: string, title: string, isGame: boolean): string {
  let processed = html;

  if (!processed.includes("<!DOCTYPE html>")) {
    processed = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>${title}</title>
  ${!isGame && !processed.includes("tailwindcss") ? '<script src="https://cdn.tailwindcss.com"></script>' : ""}
</head>
<body>
${processed}
</body>
</html>`;
  }

  // Inject keyboard listener focus for games
  if (isGame && !processed.includes("window.focus()")) {
    const focusScript = `
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        window.focus();
        const canvas = document.querySelector('canvas');
        if (canvas) {
          canvas.setAttribute('tabindex', '0');
          canvas.focus();
          canvas.addEventListener('click', () => canvas.focus());
        }
      });
    </script>
    `;
    processed = processed.replace("</body>", `${focusScript}\n</body>`);
  }

  return processed;
}
